version: 2.1

jobs:
  test:
    docker:
      - image: cimg/php:8.2.5
      - image: cimg/mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1

      - run:
          name: Install PHP Extensions
          command: sudo docker-php-ext-install pdo_mysql

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "backend/composer.json" }}
            - v1-dependencies-

      - run:
          name: composer install
          working_directory: backend
          command: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "backend/composer.json" }}
          
      - run:
          name: base64 decode env file
          command:
            echo $BACKEND_ENV_TESTING | tr -d '\n' | base64 -d > ./backend/.env.testing

      - run:
          name: Wait for db
          command: dockerize -wait tcp\://localhost:3306 -timeout 1m

      - run:
          name: Migration
          working_directory: backend
          command: sudo php artisan migrate --env=testing

      - run:
          name: Run tests
          working_directory: backend
          command: sudo php artisan test
workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - test
